# This configuration show a video from demux MKV

supstream:
    zmq_path: "tcp://0.0.0.0:5557"
    timezone: "Europe/Paris"

pipelines:

    matroska_video_0:

        init_state: null
        type_exec: thread
        auto_restart: true

        elements:
            souphttpsrc:
                element: souphttpsrc
                properties:
                    location: https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm
                element_link: matroskademux
            matroskademux:
                element: matroskademux
                pad_link:
                    pad_video:
                        from: video_0
                        to:
                            name: vp8dec
                            pad: sink
            vp8dec:
                element: vp8dec
                element_link: videoconvert
            videoconvert:
                element: videoconvert
                element_link: autovideosink
            autovideosink:
                element: autovideosink
                ready_state: "2022-04-15 09:45:00"
                paused_state: "2022-04-15 09:49:40"
                playing_state: "2022-04-15 09:50:00"
