# This configuration record micro and apply audio echo effect, save recording
# in record_audioecho.ogg file

pipelines:

    pulsesrc_audioecho_filesink:
        init_state: play
        type_exec: thread
        elements:
            pulsesrc:
                element: pulsesrc
                element_link: audioconvert
            audioconvert:
                element: audioconvert
                element_link: audioecho
            audioecho:
                element: audioecho
                properties:
                    delay: 500000000
                    intensity: 0.6
                    feedback: 0.4
                element_link: audioconvert2
            audioconvert2:
                element: audioconvert
                element_link: vorbisenc
            vorbisenc:
                element: vorbisenc
                element_link: oggmux
            oggmux:
                element: oggmux
                element_link: filesink
            filesink:
                element: filesink
                properties:
                    location: record_audioecho.ogg
