# This pipeline is a screen recorder
# gst-launch-1.0  ximagesrc  endx=1919 endy=1079 use-damage=false ! video/x-raw,framerate=15/1 ! videoconvert ! vp8enc min_quantizer=13 max_quantizer=13 cpu-used=5 deadline=1000000 threads=2 ! queue ! webmmux ! filesink location=/tmp/test.webm

supstream:
  zmq_path: "tcp://0.0.0.0:5557"

pipelines:
  screenrecorder:
    init_state: play
    type_exec: sync

    elements:
      
      ximagesrc:
        element: ximagesrc
        properties:
          endx: 1079
          use-damage: false
        caps:
          media_type: video/x-raw
          framerate: "15/1"
        element_link: videoconvert

      videoconvert:
        element: videoconvert
        element_link: vp8enc

      vp8enc:
        element: vp8enc
        properties:
          min_quatizer: 13
          max_quantizer: 13
          cpu-used: 5
          deadline: 1000000
          threads: 2
        element_link: queue

      queue:
        element: queue
        element_link: webmmux

      webmmux:
        element: webmmux
        element_link: filesink

      filesink:
        element: filesink
        properties:
          location: desktop.ogg
