# gst-launch-1.0 multifilesrc location="IMG_%04d.jpg" index=0001 loop=0 caps="image/jpeg,framerate=1/6" ! jpegdec ! videoconvert ! videoscale ! glimagesink   filesrc location=ourkitycat.mp3 ! mpegaudioparse ! mpg123audiodec ! audioconvert ! pulsesink

supstream:
    zmq_path: "tcp://0.0.0.0:5557"

pipelines:

    slideshow_img:

        init_state: play
        type_exec: thread

        elements:

            multifilesrc:
                element: multifilesrc
                properties:
                    location: "/tmp/images/image-%03d.png"
                    index: 1
                    caps: "image/png,framerate=(fraction)12/1"
                element_link: pngdec

            pngdec:
                element: pngdec
                element_link: videoconvert
            
            videoconvert:
                element: videoconvert
                element_link: videoscale

            videoscale:
                element: videoscale
                element_link: glimagesink

            glimagesink:
                element: glimagesink

    slideshow_audio:

        init_state: play
        type_exec: thread

        elements:

            filesrc:
                element: filesrc
                properties:
                    location: "/tmp/slideshow.mp3"
                element_link: mpegaudioparse

            mpegaudioparse:
                element: mpegaudioparse
                element_link: mpg123audiodec

            mpg123audiodec:
                element: mpg123audiodec
                element_link: audioconvert

            audioconvert:
                element: audioconvert
                element_link: autoaudiosink

            autoaudiosink:
                element: autoaudiosink
