# gst-launch-1.0 multifilesrc location="img.%04d.png" index=0 caps="image/png,framerate=\(fraction\)12/1" \
# ! pngdec ! videoconvert ! videorate ! theoraenc \
# ! oggmux ! filesink location="images.ogg"

supstream:
    zmq_path: "tcp://0.0.0.0:5557"

pipelines:

    slideshow_img:

        init_state: play
        type_exec: sync

        elements:

            multifilesrc:
                element: multifilesrc
                properties:
                    location: "/tmp/images/image-%03d.png"
                    index: 0
                    caps: "image/png,framerate=(fraction)12/1"
                element_link: pngdec

            pngdec:
                element: pngdec
                element_link: videoconvert
            
            videoconvert:
                element: videoconvert
                element_link: videorate

            videorate:
                element: videorate
                element_link: theoraenc

            theoraenc:
                element: theoraenc
                element_link: oggmux

            oggmux:
                element: oggmux
                element_link: filesink

            filesink:
                element: filesink
                properties:
                    location: "images.ogg"
