# This configuration launch videotestsrc on autovideosink using caps

pipelines:

    videotestsrc_videoconvert_autovideosink:

        init_state: play
        type_exec: thread

        elements:
            src:
                element: videotestsrc
                element_link: videoconvert
                caps:
                    media_type: video/x-raw
                    format: YUY2
            videoconvert:
                element: videoconvert
                element_link: sink
            sink:
                element: autovideosink

