# This configuration launch videotestsrc on autovideosink using caps

pipelines:

    videotestsrc_autovideosink:

        init_state: play
        type_exec: thread

        elements:
            src:
                element: videotestsrc
                element_link: sink
                caps:
                    media_type: video/x-raw
                    format: I420
            sink:
                element: autovideosink

