# This sample show wavescope from the voice recorder
# gst-launch-1.0 pulsesrc ! audioconvert ! wavescope ! ximagesink

supstream:
    zmq_path: "tcp://0.0.0.0:5557"

pipelines:

    wavescope:

        init_state: play
        type_exec: thread

        elements:

          pulsesrc:
            element: pulsesrc
            element_link: audioconvert

          audioconvert:
            element: audioconvert
            element_link: wavescope

          wavescope:
            element: wavescope
            element_link: ximagesink

          ximagesink:
            element: ximagesink

    spacescope:

        init_state: play
        type_exec: thread

        elements:

          pulsesrc_2:
            element: pulsesrc
            element_link: audioconvert_2

          audioconvert_2:
            element: audioconvert
            element_link: spacescope_2

          spacescope_2:
            element: spacescope
            element_link: ximagesink_2

          ximagesink_2:
            element: ximagesink
