# This configuration create 2 pipelines, one for video, one for audio

pipelines:

    matroska-video_0:

        init_state: play
        type_exec: thread

        elements:
            souphttpsrc:
                element: souphttpsrc
                properties:
                    location: https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm
                element_link: matroskademux
            matroskademux:
                element: matroskademux
                pad_link:
                    pad_video:
                        from: video_0
                        to:
                            name: vp8dec
                            pad: sink
            vp8dec:
                element: vp8dec
                element_link: videoconvert
            videoconvert:
                element: videoconvert
                element_link: shagadelictv
            shagadelictv:
                element: shagadelictv
                element_link: videoconvert2
            videoconvert2:
                element: videoconvert
                element_link: autovideosink
            autovideosink:
                element: autovideosink
    
    matroska-audio_0:

        init_state: play
        type_exec: thread

        elements:
            souphttpsrc:
                element: souphttpsrc
                properties:
                    location: https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm
                element_link: matroskademux
            matroskademux:
                element: matroskademux
                pad_link:
                    pad_audio:
                        from: audio_0
                        to:
                            name: vorbisdec
                            pad: sink
            vorbisdec:
                element: vorbisdec
                element_link: audioconvert
            audioconvert:
                element: audioconvert
                element_link: audioecho
            audioecho:
                element: audioecho
                properties:
                    delay: 500000000
                    intensity: 0.6
                    feedback: 0.4
                element_link: audioconvert2
            audioconvert2:
                element: audioconvert
                element_link: autoaudiosink
            autoaudiosink:
                element: autoaudiosink
                properties:
                    location: sintel_trailer_audio_0.ogg
