supstream:

    zmq_path: "tcp://0.0.0.0:5557"

pipelines:

    web-overlay-speaker:

        init_state: play
        type_exec: thread

        elements:

            ########
            # DASH #
            ########

            dashsink:
                element: dashsink
                properties:
                    mpd-root-path: /tmp
                    target-duration: 60
                    dynamic: false
                    period-duration: 60000
                    muxer: ts

            ###############
            # WEB OVERLAY #
            ###############

            cefsrc:
                element: cefsrc
                properties:
                    url: https://math.hws.edu/eck/js/mandelbrot/MB.html
                element_link: cefdemux
                caps:
                    media_type: video/x-raw
                    width: 1920
                    height: 1080

            cefdemux:
                element: cefdemux
                pad_link:

                    pad_video:
                        from: video
                        to:
                            name: videoconvert
                            pad: sink

            videoconvert:
                element: videoconvert
                element_link: queue
                pad_link:

                    pad_video:
                        from: src
                        to:
                            name: queue
                            pad: sink

            queue:
                element: queue
                element_link: x264enc

            x264enc:
                element: x264enc
                properties:
                    bitrate: 400
                pad_link:
                    pad_video:
                        from: src
                    to:
                        name: dashsink
                        pad: video_0

            #################
            # AUDIO SPEAKER #
            #################

            pulsesrc:
                element: pulsesrc
                element_link: audioconvert

            audioconvert:
                element: audioconvert
                pad_link:

                    pad_audio_speaker:
                        from: src
                        to:
                            name: dashsink
sh: 1: q: not found

